outputFolder:  ../results/LR_calling/
tempFolder: /scratch/mshokrof/



svCallingTools:
   - sniffles:
      - minimap2
   - pbsv:
      - minimap2
   - cuteSV:
      - minimap2      

vep:
   plugins:
   # Add any plugin from https://www.ensembl.org/info/docs/tools/vep/script/vep_plugins.html
   # Plugin args can be passed as well, e.g. "LoFtool,path/to/custom/scores.txt".
      - LoFtool
    # extra command line arguments (e.g. --sift, see docs)
   extra: ""